name: word_wardrobe
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  go_router: 9.0.3
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  flutter_bloc: 8.1.3
  bloc: 8.1.2
  path_provider: 2.0.15
  injectable: 2.1.2
  get_it: 7.6.0
  uuid: 3.0.7
  rxdart: 0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  build_runner: 2.4.6
  freezed: 2.4.1
  json_serializable: 6.7.1
  injectable_generator: 2.1.6

flutter:
  uses-material-design: true
